### PR TITLE
Add get_url() with built-in reverse() to context

### PR DESCRIPTION
**Pull request by bittner**
Resolves issue #10 

As discussed. For developers stopping for more than 10 ms when hitting `base_url + reverse('foo:bar')`, and only 8 ms when hitting `get_url(reverse('foo:bar'))`.  :grimacing:

And then there are those managers that worry about constructs that break more easily. Visually. Yes, it's about readability. Not nuclear physics.  :weary:
## New coding style possible

As documented in the docstring, alternative choices to `context.base_url` are now:

``` python
context.get_url()  # alias for context.base_url
context.get_url('/path/to/page/')
context.get_url(reverse='resource-name')  # shortcut, requires no "from ... import reverse"
context.get_url(reverse('resource-name'))
context.get_url(reverse('resource-name', 'args', and='kwargs'))
```

I would add this as a reference to the Wiki documentation as soon as the PR is merged.

### CODE REVIEW

**Comment by mixxorz** [comment]
Please include tests.

**Comment by mixxorz** [comment]
I actually don't know why this failed CI. Bad luck? Haha.

After a few nights of reflecting, I think this is a welcome addition to behave-django. Although I think it could be better. Django's `redirect` shortcut function can accept a model instance, a view name (which will be passed to `reverse`), or an absolute or relative URL. I think we can use [`django.shortcuts.resolve_url`](https://docs.djangoproject.com/en/1.8/_modules/django/shortcuts/) (the same function `redirect` uses) to mimic this behavior.

This way, the syntax would just be:

``` python
context.get_url('/absolute/url/here')
context.get_url('view_name')
context.get_url(model_instance)
```

and all of it will magically work. :laughing:

**Comment by bittner** [comment]
@mixxorz Great, that are awesome news!

That's why I love Open Source. It's a damn hard job to add your contributions sometimes, but when the conversation finally starts you get something in return that is better than what you offered.

**Comment by bittner** [comment]
There is no `django.shortcuts.resolve_url()` in Django < 1.5, hence the two tests with Django 1.4 fail. Is there a quick fix for this, or shall we provide a simplified version (e.g. using `reverse()` only) for Django < 1.5?

The Python 2.6 and Django 1.6 combination is again the "bad luck" scenario where `./manage.py behave` [returns exit code 1](https://github.com/mixxorz/behave-django/blob/master/tests.py#L14) instead of zero. We may re-activate the output to stdout/stderr temporarily to find out why.

**Comment by mixxorz** [comment]
I think we have no choice but to either:

a) Import the code for `resolve_url` into our codebase. Django 1.4 can _technically_ do it. It's just that the functionality is right inside `redirect` instead of being extracted into its own function. I personally don't want to do this as it seems very hacky and WET.

b) Simplify this feature if `django.VERSION < 1.5`. Just return `context.base_url + url`.

I'm leaning towards solution B.

About the Django 1.6 issue. I'll investigate. It didn't use to fail. :(

**Comment by bittner** [comment]
I feel it's not a beautiful idea to replicate the whole `resolve_url` code locally, hence I'll spit out a warning in Django < 1.5 and make `get_url` act as you suggest. The tests for a view name and a model instance fail now. Should we remove Django 1.4 from the test matrix all together to make the build pass, while reflecting the fully supported combinations?

**Comment by bittner** [comment]
Looks like the stdout redirection to `/dev/null` is the problem with Python 2.6 + Django 1.6. [Without the redirection](https://github.com/bittner/behave-django/blob/9224184e21fde581d13bf2ea93a7acce9ce882b6/tests.py#L12) the [build passes](https://travis-ci.org/mixxorz/behave-django/builds/65245993) for that combination.

**Comment by mixxorz** [comment]
Really? Great. I'll whip up a solution in a separate branch.

As for the tests, we can skip particular tests depending on the DJANGO environment variable. This would require tagging the feature files with a new tag (maybe `@skip-for-django14`), and writing tests.sh script for travis to execute where it will add `@skip-for-django14` as one of the skipped features when calling `python manage.py behave`.

I don't think that should be done in _this_ PR though. I'll post another issue about this, along with the `/dev/null` issue with Django 1.6.

As for this PR, I think we're good.

**Comment by bittner** [comment]
Wait! I may have come up with a solution that works even with Django 1.4. Let's see what Travis-CI says about it.

Let me know what you think about my tests. Feedback welcome!

**Comment by bittner** [comment]
The Python 2.6 + Django 1.6 problem may have been a Travis-CI issue. They had some [infrastructure issues](https://www.traviscistatus.com/) today and probably changed stuff. I noticed earlier that [build #51](https://travis-ci.org/mixxorz/behave-django/builds/65257416) had already passed for the 2.6/1.6 combination.

**Comment by mixxorz** [comment]
Wow. That's great! It's a bit hacky but whatever, it's for an old version of Django, so it's unlikely to change implementation. Thanks @bittner . I merged this in.

**Comment by bittner** [comment]
Thank you! That was all great input from you. Will you make a release with the changes? Would be nice.

Can you add the docstring of `get_url` to the Wiki? I thought, right next to where you mention the `base_url`. Looks like I can't make changes to the Wiki myself.

**Comment by mixxorz** [comment]
Sure thing! I'll do it when I draft a new release, maybe tomorrow.

**Pull request merged**
