### PR TITLE
Check rst for pypi

### PR DESCRIPTION
**Pull request by mixxorz**
I added a test for checking the rST on README.rst so that PyPi would render it properly.

### CODE REVIEW

**Comment by mixxorz** [comment]
I realized that the test doesn't necessarily have to pass on TravisCI. Just on contributors machines.

**Comment by mixxorz** [comment]
Never mind. I realized that I would be the only one worrying about PyPi rst crap.

**Comment by bittner** [comment]
Why not install `docutils` on Travis-CI in the `install` block?

**Comment by bittner** [comment]
Actually, `Sphinx` _is_ installed on Travis-CI via the [requirements-dev.txt](https://github.com/mixxorz/behave-django/blob/master/requirements-dev.txt#L8). So, why isn't the test working?

**Comment by bittner** [comment]
The build problem is probably related to this issue here: http://bugs.python.org/issue23063

**Pull request closed without merging**
