### PR TITLE
Test on django 1.8.2 and 1.7.8

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by mixxorz** [comment]
I do wonder if there's any merit in these 1.6 test failures. :expressionless:

**Comment by nikolas** [comment]
You could restart that test build and see if it happens again: https://travis-ci.org/mixxorz/behave-django/jobs/65431643

Interesting that it only occurs in python 2.7, not 3.4.

**Comment by mixxorz** [comment]
It's been happening for a couple of weeks actually. Before it used to fail on Python 2.6. Now it fails on 2.7! I'll look and see if there's any way I can inspect the test while/after it's running on Travis

**Comment by mixxorz** [comment]
In any case, this PR shouldn't affect that issue #14.

**Pull request merged**
