### PR TITLE
Add a note about instantiating factories in the usage docs

### PR DESCRIPTION
**Pull request by nikolas**
Let me know if you think this example isn't appropriate or should be in another section.

### CODE REVIEW

**Comment by mixxorz** [comment]
I think this is good. But maybe you should annotate 'factories' to an article about using factories with Django testing, just so anyone who doesn't know what factories are, can look it up.

**Comment by nikolas** [comment]
Good point, I'll annotate that.

**Comment by nikolas** [comment]
I added a link to factory_boy's documentation when I first mention factories here.

**Comment by mixxorz** [comment]
Cool. :D

**Comment by bittner** [comment]
@nikolas We're introducing an API change to behave-django in PR #28.

behave-django's `before_scenario()` will now be implicitly called _before_ the process flow enters behave's `before_scenario()`, defined by you as a user, but the fixtures are loaded _after_ the process flow leaves behave's `before_scenario()`! -- This is necessary; you couldn't specify fixtures in your user-defined `before_scenario()` otherwise.

Can you double-check this works out with factory_boy? The updated documentation is on the [use-existing-database branch](https://github.com/bittner/behave-django/blob/feature/use-existing-database/docs/usage.rst#database-transactions-per-scenario). Thank you!

**Comment by mixxorz** [comment]
As long as the database gets setup before any code in `before_scenario` runs, I think we're fine.

**Pull request merged**
